## Imports

In [3]:
import pandas as pd
import numpy as np

# Numpy

### Numpy Arrays

In [1]:
new_list = [1,2,3,4,5]

In [ ]:
## Rechenbeispiele list

In [40]:
new_array = np.array(new_list)

In [41]:
new_array[0:5] ## Index 0-4 wird ausgegeben

array([1, 2, 3, 5, 7])

In [42]:
new_array == 5 ## Masking

array([False, False, False,  True, False,  True, False,  True])

In [43]:
new_array[new_array==5] ## Anwenden der Maske

array([5, 5, 5])

In [44]:
new_array

array([1, 2, 3, 5, 7, 5, 4, 5])

In [45]:
new_array + 5 ## Mit Numpy-Arrays sind Rechenoperationen direkt anwendbar

array([ 6,  7,  8, 10, 12, 10,  9, 10])

In [46]:
new_array.shape

(8,)

In [50]:
more_dimensional_array = np.zeros(shape=(3,2))

In [53]:
more_dimensional_array[0,0] = 1 ## [row,column]
more_dimensional_array

array([[1., 0.],
       [0., 0.],
       [0., 0.]])

In [55]:
more_dimensional_array[1,0] = 2
more_dimensional_array

array([[1., 0.],
       [2., 0.],
       [0., 0.]])

In [56]:
more_dimensional_array.shape

(3, 2)

In [59]:
more_dimensional_array = more_dimensional_array * 2
more_dimensional_array

array([[2., 0.],
       [4., 0.],
       [0., 0.]])

In [65]:
np.vstack((more_dimensional_array,[2,5])) 

array([[2., 0.],
       [4., 0.],
       [0., 0.],
       [2., 5.]])

# Pandas

### Pandas Dataframe

In [66]:
## Anlegen eines Pandas-Dataframes
df = pd.DataFrame(my_dict)

In [67]:
df ## Ein DataFrame kann unterschiedliche Typen enthalten

random_text  random_number
0             lalal              1
1  das ist ein Text              5
2         mega nice              7

### Pandas Series

In [69]:
type(df.random_text)

pandas.core.series.Series

In [70]:
df.random_text

0               lalal
1    das ist ein Text
2           mega nice
Name: random_text, dtype: object

In [71]:
type(df)

pandas.core.frame.DataFrame

### Indexing

In [72]:
### iloc
df.iloc[0:2,[0]] ##[row,column]

random_text
0             lalal
1  das ist ein Text

In [73]:
### loc
df.loc[:,["random_text"]]

random_text
0             lalal
1  das ist ein Text
2         mega nice

In [74]:
### filter
df.loc[df.random_text == "lalal",['random_text']]

random_text
0       lalal

### nützliche Funktionen

In [77]:
### head
df.head()

random_text  random_number
0             lalal              1
1  das ist ein Text              5
2         mega nice              7

In [78]:
df.head(2)

random_text  random_number
0             lalal              1
1  das ist ein Text              5

In [79]:
### info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   random_text    3 non-null      object
 1   random_number  3 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 176.0+ bytes


In [80]:
### Funktionen anwenden
df['new_string']  = df.random_text.apply(lambda x: x.upper())

In [81]:
df

random_text  random_number        new_string
0             lalal              1             LALAL
1  das ist ein Text              5  DAS IST EIN TEXT
2         mega nice              7         MEGA NICE